name: Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub.yaml

jobs:
  update_description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/xpense-web
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
