name: Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  push_to_registry:
    name: Release Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - id: get_version
        uses: battila7/get-version-action@v2

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/xpense-web:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/xpense-web:${{ steps.get_version.outputs.major }}
            ${{ secrets.DOCKERHUB_USERNAME }}/xpense-web:${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}
            ${{ secrets.DOCKERHUB_USERNAME }}/xpense-web:${{ steps.get_version.outputs.version-without-v }}
