name: Test building the Docker image

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test building the Docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Try to build the image
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
